# Generated by Django 3.2.8 on 2021-10-26 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.date(2021, 10, 26)),
        ),
    ]
